{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-main-servicemonitor
  namespace: canary-demo
  release: prometheus
  labels:
    app: {{ .Release.Name }}
spec:
  serviceMonitorSelector:
    namespaceSelector:
      - canary-demo
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
  - port: http
    path: /metrics

---
{{- if .Values.canary.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-canary-servicemonitor
  namespace: canary-demo
  release: prometheus
  labels:
    app: {{ .Release.Name }}-canary
spec:
  serviceMonitorSelector:
    namespaceSelector:
      - canary-demo
  selector:
    matchLabels:
      app: {{ .Release.Name }}-canary
  endpoints:
  - port: http
    path: /metrics
{{- end }}
{{- end }}